---
name: PR Tests

on:
  pull_request:
    branches:
      - master

env:
  IMAGE_TAG: latest

jobs:
  build:
    name: Build and Test

    runs-on: ubuntu-latest

    env:
      ENV: ci

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install Node Modules
        run: npm ci

      - name: Run Unit Tests
        run: npm run test:ci
