---
name: PR Tests

on:
  pull_request:
    branches:
      - master

env:
  IMAGE_TAG: latest

jobs:
  build:
    name: Build and Test

    runs-on: ubuntu-latest

    env:
      ENV: ci

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Setup latest LTS Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install Node Modules
        run: npm ci --ignore-scripts

      - name: Run Npm Package Check
        run: npm run pkg-chk

      - name: Run Formatting Checks
        run: npm run format:ci

      - name: Run Type Checks
        run: npm run type

      - name: Run Linting Checks
        run: npm run lint:ci

      - name: Run Unit Tests
        run: npm run test:ci

      - name: Run Build
        run: npm run build

      - name: Ensure latest build output is included
        run: "[[ -z $(git diff --name-only) ]]"
        shell: bash
